name: Primer workflow
on: push
jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Bajar codigo
        run: actions/checkout@v4
      - name: probar codigo
        run: python3 main.py


  build_push:
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar mensaje
        run: echo "Hola github actions"
      - name: Bajar codigo
        uses: actions/checkout@v4
      - name: Probar codigo
        run: python3 main.py
      
